# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'
variables:
  imageName: sh360web:$(build.buildId)'
steps:
#- script: docker build -f Dockerfile -t $(imageName) .
#  displayName: 'docker build'
- task: Docker@1
  inputs:
    azureSubscriptionEndpoint: RMPM
    azureContainerRegistry: shregistry.azurecr.io
    dockerFile: Source/SmartHotel360.Website/Dockerfile
    useDefaultContext: false
    buildContext: Source/SmartHotel360.Website
    imageName: '$(imageName)'
    includeLatestTag: true
- task: Docker@1
  inputs:
    azureSubscriptionEndpoint: RMPM
    azureContainerRegistry: shregistry.azurecr.io
    command: 'Push an image'
    imageName: '$(imageName)'
    includeLatestTag: true
- task: Docker@1
  inputs:
    azureSubscriptionEndpoint: RMPM
    azureContainerRegistry: shregistry.azurecr.io
    command: 'Push an image'
    imageName: 'sh360web:latest'
    includeLatestTag: true
